<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="0.0000" tests="1" failures="2">
  <testsuite name="Root Suite" timestamp="2022-03-01T07:47:58" tests="0" file="cypress/integration/01-publisher/013-api-product/07-create-product-and-update-underline-api.spec.js" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="Mock the api response and test it" timestamp="2022-03-01T07:47:58" tests="1" time="0.0000" failures="2">
    <testcase name="Mock the api response and test it Mock the api response and test it" time="0.0000" classname="Mock the api response and test it">
      <failure message="Timed out retrying after 10000ms: Expected to find element: `[data-testid=&quot;resource-wrapper&quot;] ul li:last-child button`, but never found it." type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 10000ms: Expected to find element: `[data-testid="resource-wrapper"] ul li:last-child button`, but never found it.
    at Context.eval (https://localhost:9443/__cypress/tests?p=cypress/integration/01-publisher/013-api-product/07-create-product-and-update-underline-api.spec.js:208:14)]]></failure>
    </testcase>
    <testcase name="Mock the api response and test it &quot;after all&quot; hook for &quot;Mock the api response and test it&quot;" time="0.0000" classname="&quot;after all&quot; hook for &quot;Mock the api response and test it&quot;">
      <failure message="`cy.click()` failed because it requires a DOM element.

The subject received was:

  &gt; `undefined`

The previous command that ran was:

  &gt; `cy.get()`

Because this error occurred during a `after all` hook we are skipping the remaining tests in the current suite: `Mock the api response and t...`" type="CypressError"><![CDATA[CypressError: `cy.click()` failed because it requires a DOM element.

The subject received was:

  > `undefined`

The previous command that ran was:

  > `cy.get()`

Because this error occurred during a `after all` hook we are skipping the remaining tests in the current suite: `Mock the api response and t...`
    at ensureElement (https://localhost:9443/__cypress/runner/cypress_runner.js:162678:76)
    at validateType (https://localhost:9443/__cypress/runner/cypress_runner.js:162501:16)
    at $Cy.ensureSubjectByType (https://localhost:9443/__cypress/runner/cypress_runner.js:162537:9)
    at pushSubjectAndValidate (https://localhost:9443/__cypress/runner/cypress_runner.js:171827:12)
    at Context.<anonymous> (https://localhost:9443/__cypress/runner/cypress_runner.js:172102:20)
From Your Spec Code:
    at Context.eval (https://localhost:9443/__cypress/tests?p=cypress/support/index.js:274:66)]]></failure>
    </testcase>
  </testsuite>
</testsuites>